### PR TITLE
docs: added the homepage

### PR DESCRIPTION
**Pull request by SinchanaMS**
Created the Home Page.

image

image

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Amazing work, good code, your work always amazes me, can't find any changes to be made as of now, appreciate the efforts you have made. Keep it up.

**Review by Debarshi95 — APPROVED** [review]
Looks good.

**Review by kushalsourav — APPROVED** [review]
Everything is good

**Comment by SinchanaMS** [comment]
Thank you for the review! 
Merging to dev.

**Pull request merged**
